# Generated by Django 5.2.8 on 2025-12-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('logo_igdb_id', models.CharField(blank=True, help_text='ID логотипа в IGDB', max_length=50, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cached_usage_count', models.IntegerField(default=0)),
                ('last_count_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Keyword Categories',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('storyline', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(default=0)),
                ('first_release_date', models.DateTimeField(blank=True, null=True)),
                ('series_order', models.PositiveIntegerField(blank=True, help_text='Порядковый номер в серии (1, 2, 3...). Если игра в нескольких сериях, это относится к основной серии.', null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('developers', models.ManyToManyField(blank=True, related_name='developed_games', to='games.company')),
                ('publishers', models.ManyToManyField(blank=True, related_name='published_games', to='games.company')),
                ('game_modes', models.ManyToManyField(blank=True, to='games.gamemode')),
                ('genres', models.ManyToManyField(blank=True, to='games.genre')),
                ('keywords', models.ManyToManyField(blank=True, to='games.keyword')),
                ('platforms', models.ManyToManyField(blank=True, to='games.platform')),
                ('player_perspectives', models.ManyToManyField(blank=True, to='games.playerperspective')),
            ],
            options={
                'ordering': ['-rating_count'],
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='games.keywordcategory'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('image_url', models.URLField()),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.game')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('is_main_series', models.BooleanField(default=True, help_text='Основная серия (не спин-офф)')),
                ('parent_series', models.ForeignKey(blank=True, help_text='Родительская серия, если это подсерия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subseries', to='games.series')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.series'),
        ),
        migrations.AddField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(blank=True, to='games.theme'),
        ),
        migrations.CreateModel(
            name='GameSimilarityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_source', to='games.game')),
                ('game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_target', to='games.game')),
            ],
            options={
                'verbose_name_plural': 'Game similarity cache',
                'indexes': [models.Index(fields=['game1', '-similarity_score'], name='games_games_game1_i_6cb418_idx'), models.Index(fields=['game2', '-similarity_score'], name='games_games_game2_i_3b4075_idx')],
                'unique_together': {('game1', 'game2')},
            },
        ),
    ]
