# Generated by Django 5.2.8 on 2025-12-24 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('logo_igdb_id', models.CharField(blank=True, help_text='Logo ID in IGDB', max_length=50, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='games_compa_name_b953a9_idx'), models.Index(fields=['igdb_id'], name='games_compa_igdb_id_098c4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='games_gamem_name_e774cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='games_genre_name_f4ac62_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Keyword Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='games_keywo_name_829b6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('cached_usage_count', models.IntegerField(db_index=True, default=0)),
                ('last_count_update', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='games.keywordcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='games_platf_name_c75c65_idx'), models.Index(fields=['slug'], name='games_platf_slug_dce524_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='games_playe_name_013e45_idx')],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('game_type', models.IntegerField(blank=True, choices=[(0, 'Main game'), (4, 'Standalone expansion'), (7, 'Season'), (8, 'Remake'), (9, 'Remaster'), (10, 'Expanded game'), (1, 'DLC/Addon'), (2, 'Expansion'), (3, 'Bundle'), (5, 'Mod'), (6, 'Episode'), (11, 'Port'), (12, 'Fork'), (13, 'Pack / Addon'), (14, 'Update')], db_index=True, help_text='Game type from IGDB', null=True)),
                ('version_title', models.CharField(blank=True, help_text='Version title', max_length=255, null=True)),
                ('rawg_description', models.TextField(blank=True, help_text='Game description imported from RAWG.io', null=True, verbose_name='Description (RAWG)')),
                ('storyline', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('rating_count', models.IntegerField(db_index=True, default=0)),
                ('first_release_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('series_order', models.PositiveIntegerField(blank=True, help_text='Order in series (1, 2, 3...)', null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('wiki_description', models.TextField(blank=True, help_text='Game description from Wikipedia (Gameplay section)', null=True, verbose_name='Description (Wikipedia)')),
                ('_cached_genre_count', models.IntegerField(blank=True, editable=False, null=True)),
                ('_cached_keyword_count', models.IntegerField(blank=True, editable=False, null=True)),
                ('_cached_platform_count', models.IntegerField(blank=True, editable=False, null=True)),
                ('_cached_developer_count', models.IntegerField(blank=True, editable=False, null=True)),
                ('_cache_updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('developers', models.ManyToManyField(blank=True, related_name='developed_games', to='games.company')),
                ('parent_game', models.ForeignKey(blank=True, help_text='Parent game (for DLC, expansions, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_games', to='games.game')),
                ('publishers', models.ManyToManyField(blank=True, related_name='published_games', to='games.company')),
                ('version_parent', models.ForeignKey(blank=True, help_text='Version parent (base version of the game)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_children', to='games.game')),
                ('game_modes', models.ManyToManyField(blank=True, to='games.gamemode')),
                ('genres', models.ManyToManyField(blank=True, to='games.genre')),
                ('keywords', models.ManyToManyField(blank=True, to='games.keyword')),
                ('platforms', models.ManyToManyField(blank=True, to='games.platform')),
                ('player_perspectives', models.ManyToManyField(blank=True, to='games.playerperspective')),
            ],
            options={
                'ordering': ['-rating_count'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('image_url', models.URLField(max_length=500)),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.game')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('is_main_series', models.BooleanField(default=True, help_text='Основная серия (не спин-офф)')),
                ('parent_series', models.ForeignKey(blank=True, help_text='Родительская серия, если это подсерия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subseries', to='games.series')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.series'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='games_theme_name_813d51_idx')],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(blank=True, to='games.theme'),
        ),
        migrations.CreateModel(
            name='GameCountsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres_count', models.IntegerField(default=0)),
                ('keywords_count', models.IntegerField(default=0)),
                ('themes_count', models.IntegerField(default=0)),
                ('developers_count', models.IntegerField(default=0)),
                ('perspectives_count', models.IntegerField(default=0)),
                ('game_modes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counts_cache', to='games.game')),
            ],
            options={
                'indexes': [models.Index(fields=['game'], name='games_gamec_game_id_676bac_idx'), models.Index(fields=['updated_at'], name='games_gamec_updated_3ed604_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameSimilarityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(db_index=True)),
                ('calculated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_source', to='games.game')),
                ('game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_target', to='games.game')),
            ],
            options={
                'verbose_name_plural': 'Game similarity cache',
                'indexes': [models.Index(fields=['game1', '-similarity_score'], name='games_games_game1_i_6cb418_idx'), models.Index(fields=['game2', '-similarity_score'], name='games_games_game2_i_3b4075_idx'), models.Index(fields=['calculated_at'], name='games_games_calcula_29fba8_idx')],
                'unique_together': {('game1', 'game2')},
            },
        ),
        migrations.CreateModel(
            name='GameSimilarityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_genres', models.IntegerField(default=0)),
                ('common_keywords', models.IntegerField(default=0)),
                ('common_themes', models.IntegerField(default=0)),
                ('common_developers', models.IntegerField(default=0)),
                ('common_perspectives', models.IntegerField(default=0)),
                ('common_game_modes', models.IntegerField(default=0)),
                ('calculated_similarity', models.FloatField(db_index=True, default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('source_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_details_as_source', to='games.game')),
                ('target_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_details_as_target', to='games.game')),
            ],
            options={
                'verbose_name': 'Game similarity detail',
                'verbose_name_plural': 'Game similarity details',
                'indexes': [models.Index(fields=['source_game', 'calculated_similarity'], name='games_games_source__ee002e_idx'), models.Index(fields=['calculated_similarity'], name='games_games_calcula_160a70_idx'), models.Index(fields=['updated_at'], name='games_games_updated_792f39_idx')],
                'unique_together': {('source_game', 'target_game')},
            },
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['cached_usage_count'], name='games_keywo_cached__3ac5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['name'], name='games_keywo_name_6d63a5_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['category', 'cached_usage_count'], name='games_keywo_categor_47aac7_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['game', 'is_primary'], name='games_scree_game_id_ce4d05_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['created_at'], name='games_scree_created_0c075f_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['name'], name='games_serie_name_a5eeec_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['slug'], name='games_serie_slug_c0ef15_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['is_main_series'], name='games_serie_is_main_1aca51_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-rating_count'], name='games_game_rating__877167_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-rating'], name='games_game_rating_393a07_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='games_game_name_1d957c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-first_release_date'], name='games_game_first_r_19c64a_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['igdb_id'], name='games_game_igdb_id_e08c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['game_type'], name='games_game_game_ty_74ef46_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['id', 'name'], name='games_game_id_dd2f11_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['summary', 'storyline', 'rawg_description', 'wiki_description'], name='games_game_summary_ad2935_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['_cached_genre_count'], name='games_game__cached_2ad22f_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['_cached_keyword_count'], name='games_game__cached_091432_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['_cached_platform_count'], name='games_game__cached_8e9615_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['_cached_developer_count'], name='games_game__cached_84e04c_idx'),
        ),
    ]
