# Generated by Django 5.2.8 on 2025-12-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-rating_count'], name='games_game_rating__877167_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-rating'], name='games_game_rating_393a07_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='games_game_name_1d957c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-first_release_date'], name='games_game_first_r_19c64a_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['igdb_id'], name='games_game_igdb_id_e08c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['cached_usage_count'], name='games_keywo_cached__3ac5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['name'], name='games_keywo_name_6d63a5_idx'),
        ),
    ]
