# Generated by Django 5.2.8 on 2026-04-19 14:40

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension
from django.contrib.postgres.indexes import GinIndex


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='game',
            index=GinIndex(
                fields=['name'],
                name='game_name_trgm_idx',
                opclasses=['gin_trgm_ops'],
            ),
        ),
    ]