# Generated by Django 5.2.8 on 2025-12-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['rating_count', 'rating'], name='games_game_rating__3702b5_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['rating_count', '-rating'], name='games_game_rating__e53082_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['rating', '-rating_count'], name='games_game_rating_fe6fec_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-first_release_date', 'game_type'], name='games_game_first_r_ba26f6_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['game_type', '-first_release_date'], name='games_game_game_ty_e0a84d_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['rating_count', 'game_type', '-rating'], name='games_game_rating__c3cdd4_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['first_release_date', 'game_type'], name='games_game_first_r_cb8934_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['game_type', 'rating_count'], name='games_game_game_ty_2e6095_idx'),
        ),
    ]
