# Generated by Django 5.2.8 on 2025-12-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_games_game_rating__3702b5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_analyzed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего анализа'),
        ),
    ]
