# Generated by Django 5.2.8 on 2025-12-11 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_games_game_rating__877167_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCountsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres_count', models.IntegerField(default=0)),
                ('keywords_count', models.IntegerField(default=0)),
                ('themes_count', models.IntegerField(default=0)),
                ('developers_count', models.IntegerField(default=0)),
                ('perspectives_count', models.IntegerField(default=0)),
                ('game_modes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counts_cache', to='games.game')),
            ],
        ),
    ]
