# Generated by Django 5.2.8 on 2025-11-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_keyword_popularity_score_keyword_usage_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSimilarityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_source', to='games.game')),
                ('game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_target', to='games.game')),
            ],
            options={
                'verbose_name_plural': 'Game similarity cache',
                'indexes': [models.Index(fields=['game1', '-similarity_score'], name='games_games_game1_i_6cb418_idx'), models.Index(fields=['game2', '-similarity_score'], name='games_games_game2_i_3b4075_idx')],
                'unique_together': {('game1', 'game2')},
            },
        ),
    ]
