# Generated by Django 5.2.8 on 2026-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_add_trigram_search_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='game_name_trgm_idx',
        ),
        migrations.AddField(
            model_name='gamecardcache',
            name='screenshots_json',
            field=models.JSONField(default=list, verbose_name='Screenshots JSON'),
        ),
        migrations.AlterField(
            model_name='gamecardcache',
            name='template_version',
            field=models.CharField(default='v2', max_length=10, verbose_name='Template version'),
        ),
    ]
