# Generated by Django 5.2.8 on 2025-12-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamecountscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSimilarityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_genres', models.IntegerField(default=0)),
                ('common_keywords', models.IntegerField(default=0)),
                ('common_themes', models.IntegerField(default=0)),
                ('common_developers', models.IntegerField(default=0)),
                ('common_perspectives', models.IntegerField(default=0)),
                ('common_game_modes', models.IntegerField(default=0)),
                ('calculated_similarity', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_details_as_source', to='games.game')),
                ('target_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_details_as_target', to='games.game')),
            ],
            options={
                'verbose_name': 'Game similarity detail',
                'verbose_name_plural': 'Game similarity details',
                'indexes': [models.Index(fields=['source_game', 'calculated_similarity'], name='games_games_source__ee002e_idx'), models.Index(fields=['calculated_similarity'], name='games_games_calcula_160a70_idx')],
                'unique_together': {('source_game', 'target_game')},
            },
        ),
    ]
