# Generated by Django 5.2.8 on 2025-12-30 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_last_analyzed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['created_at'], name='games_keywo_created_6d78dc_idx'),
        ),
    ]
