# Generated by Django 5.2.8 on 2025-11-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Bootstrap Icons class name (e.g., bi-playstation, bi-xbox)', max_length=50, null=True),
        ),
    ]
