# Generated by Django 5.2.8 on 2026-01-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_keyword_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo_igdb_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_url',
        ),
    ]
