# Generated by Django 5.2.8 on 2025-12-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamesimilaritydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mobygames_description',
            field=models.TextField(blank=True, help_text='Описание игры, импортированное с MobyGames.com', null=True, verbose_name='Описание (MobyGames)'),
        ),
    ]
