# Generated by Django 5.2.8 on 2025-11-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_platform_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
