# Generated by Django 5.2.8 on 2025-12-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_mobygames_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mobygames_description',
        ),
        migrations.AddField(
            model_name='game',
            name='rawg_description',
            field=models.TextField(blank=True, help_text='Описание игры, импортированное с RAWG.io', null=True, verbose_name='Описание (RAWG)'),
        ),
    ]
