# Generated by Django 5.2.8 on 2026-01-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_company_logo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_added',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-date_added'], name='games_game_date_ad_b36c2b_idx'),
        ),
    ]
