# Generated by Django 5.2.8 on 2025-12-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_mobygames_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(help_text='ID типа игры в IGDB', unique=True)),
                ('name', models.CharField(help_text='Название типа (main_game, dlc_addon и т.д.)', max_length=100)),
                ('display_name', models.CharField(help_text='Отображаемое название типа', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание типа')),
                ('is_primary', models.BooleanField(default=True, help_text='Является ли тип основной игрой')),
                ('is_dlc', models.BooleanField(default=False, help_text='DLC/Дополнение')),
                ('is_expansion', models.BooleanField(default=False, help_text='Расширение')),
                ('is_bundle_component', models.BooleanField(default=False, help_text='Бандл')),
                ('is_standalone_expansion', models.BooleanField(default=False, help_text='Стенд-алоне расширение')),
                ('is_mod', models.BooleanField(default=False, help_text='Мод')),
                ('is_episode', models.BooleanField(default=False, help_text='Эпизод')),
                ('is_season', models.BooleanField(default=False, help_text='Сезон')),
                ('is_remake', models.BooleanField(default=False, help_text='Ремейк')),
                ('is_remaster', models.BooleanField(default=False, help_text='Ремастер')),
                ('is_expanded_game', models.BooleanField(default=False, help_text='Расширенное издание')),
                ('is_port', models.BooleanField(default=False, help_text='Порт')),
                ('is_fork', models.BooleanField(default=False, help_text='Форк')),
                ('is_pack_addon', models.BooleanField(default=False, help_text='Pack/Addon')),
                ('is_update', models.BooleanField(default=False, help_text='Обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип игры',
                'verbose_name_plural': 'Типы игр',
                'ordering': ['igdb_id'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='parent_game',
            field=models.ForeignKey(blank=True, help_text='Родительская игра (для DLC, расширений и т.д.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_games', to='games.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='parent_game_igdb_id',
            field=models.IntegerField(blank=True, help_text='ID родительской игры в IGDB', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='version_parent_igdb_id',
            field=models.IntegerField(blank=True, help_text='ID версии-родителя в IGDB', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='version_title',
            field=models.CharField(blank=True, help_text='Название версии', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(blank=True, help_text='Тип игры (main_game, DLC и т.д.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.gametype'),
        ),
    ]
