# Generated by Django 5.2.8 on 2025-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_company_gamemode_playerperspective_series_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='series',
        ),
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.series'),
        ),
    ]
