# Generated by Django 5.2.8 on 2025-12-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gametype_game_parent_game_game_parent_game_igdb_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='parent_game_igdb_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='version_parent_igdb_id',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_bundle_component',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_dlc',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_episode',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_expanded_game',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_expansion',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_fork',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_mod',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_pack_addon',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_port',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_remake',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_remaster',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_season',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_standalone_expansion',
        ),
        migrations.RemoveField(
            model_name='gametype',
            name='is_update',
        ),
        migrations.AddField(
            model_name='game',
            name='version_parent',
            field=models.ForeignKey(blank=True, help_text='Версия-родитель (базовая версия игры)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_children', to='games.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='series_order',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер в серии (1, 2, 3...)', null=True),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='name',
            field=models.CharField(help_text='Название типа игры (Основная игра, DLC/Дополнение и т.д.)', max_length=100),
        ),
    ]
