# Generated by Django 5.2.8 on 2026-01-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_add_indexes_for_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
