# Generated by Django 5.2.8 on 2025-12-03 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_game_series_game_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='is_main_series',
            field=models.BooleanField(default=True, help_text='Основная серия (не спин-офф)'),
        ),
        migrations.AddField(
            model_name='series',
            name='parent_series',
            field=models.ForeignKey(blank=True, help_text='Родительская серия, если это подсерия', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subseries', to='games.series'),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='series_order',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер в серии (1, 2, 3...). Если игра в нескольких сериях, это относится к основной серии.', null=True),
        ),
    ]
