# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0008_remove_game_parent_game_igdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type_new',
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 'Main game'),
                    (1, 'DLC/Addon'),
                    (2, 'Expansion'),
                    (3, 'Bundle'),
                    (4, 'Standalone expansion'),
                    (5, 'Mod'),
                    (6, 'Episode'),
                    (7, 'Season'),
                    (8, 'Remake'),
                    (9, 'Remaster'),
                    (10, 'Expanded game'),
                    (11, 'Port'),
                    (12, 'Fork'),
                    (13, 'Pack / Addon'),
                    (14, 'Update'),
                ],
                help_text='New game type field (for migration)',
                null=True
            ),
        ),
    ]