# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations


def copy_game_type_data(apps, schema_editor):
    """
    Copy data from game_type (ForeignKey) to game_type_new (IntegerField)
    """
    Game = apps.get_model('games', 'Game')
    GameType = apps.get_model('games', 'GameType')

    print("\n" + "=" * 60)
    print("Copying game type data...")
    print("=" * 60)

    # Сначала убедимся, что все нужные GameType существуют
    game_type_definitions = [
        (0, 'Main game', 'Основная игра', True),
        (1, 'DLC/Addon', 'DLC/Дополнение', False),
        (2, 'Expansion', 'Расширение', False),
        (3, 'Bundle', 'Бандл', False),
        (4, 'Standalone expansion', 'Стенд-алоне расширение', True),
        (5, 'Mod', 'Мод', False),
        (6, 'Episode', 'Эпизод', False),
        (7, 'Season', 'Сезон', True),
        (8, 'Remake', 'Ремейк', True),
        (9, 'Remaster', 'Ремастер', True),
        (10, 'Expanded game', 'Расширенное издание', True),
        (11, 'Port', 'Порт', False),
        (12, 'Fork', 'Форк', False),
        (13, 'Pack / Addon', 'Pack / Addon', False),
        (14, 'Update', 'Обновление', False),
    ]

    for igdb_id, name, description, is_primary in game_type_definitions:
        GameType.objects.update_or_create(
            igdb_id=igdb_id,
            defaults={
                'name': name,
                'description': description,
                'is_primary': is_primary,
            }
        )

    print(f"✓ Ensured {len(game_type_definitions)} game types exist")

    # Теперь копируем данные
    games = Game.objects.all().select_related('game_type')
    total = games.count()
    migrated = 0

    for game in games:
        if game.game_type:
            # Копируем igdb_id из GameType в game_type_new
            game.game_type_new = game.game_type.igdb_id
            game.save(update_fields=['game_type_new'])
            migrated += 1

        if migrated % 100 == 0:
            print(f"  Processed {migrated}/{total} games")

    print(f"✓ Copied data for {migrated} games")

    # Статистика
    print("\nMigration statistics:")
    for igdb_id, name, _, _ in game_type_definitions:
        count = Game.objects.filter(game_type_new=igdb_id).count()
        if count > 0:
            print(f"  {name}: {count}")

    null_count = Game.objects.filter(game_type_new__isnull=True).count()
    print(f"  No game type: {null_count}")

    print("=" * 60)
    print("Data copy complete!")
    print("=" * 60)


def reverse_copy(apps, schema_editor):
    """
    Reverse the copy operation
    """
    Game = apps.get_model('games', 'Game')
    print("\nReversing game type data copy...")
    Game.objects.update(game_type_new=None)
    print("✓ Cleared game_type_new field")


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0009_add_game_type_new_field'),
    ]

    operations = [
        migrations.RunPython(copy_game_type_data, reverse_copy),
    ]