# Generated by Django 5.2.8 on 2026-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_first_release_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamesimilaritydetail',
            index=models.Index(fields=['source_game', 'common_genres', 'calculated_similarity'], name='games_games_source__535baf_idx'),
        ),
    ]
