# Generated by Django 5.2.8 on 2026-02-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gamesimilaritydetail_games_games_source__535baf_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последнего обновления'),
        ),
    ]
