# Generated by Django 5.2.8 on 2025-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_country_alter_company_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='usage_count',
            new_name='cached_usage_count',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='popularity_score',
        ),
        migrations.AddField(
            model_name='keyword',
            name='last_count_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
