# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0010_copy_game_type_data'),
    ]

    operations = [
        # 1. Удаляем старое поле game_type (ForeignKey)
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),

        # 2. Переименовываем game_type_new в game_type
        migrations.RenameField(
            model_name='game',
            old_name='game_type_new',
            new_name='game_type',
        ),

        # 3. Изменяем поле, чтобы оно соответствовало нашему enum
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 'Main game'),
                    (1, 'DLC/Addon'),
                    (2, 'Expansion'),
                    (3, 'Bundle'),
                    (4, 'Standalone expansion'),
                    (5, 'Mod'),
                    (6, 'Episode'),
                    (7, 'Season'),
                    (8, 'Remake'),
                    (9, 'Remaster'),
                    (10, 'Expanded game'),
                    (11, 'Port'),
                    (12, 'Fork'),
                    (13, 'Pack / Addon'),
                    (14, 'Update'),
                ],
                help_text='Game type from IGDB',
                null=True
            ),
        ),
    ]