# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0011_replace_game_type_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameType',
        ),
    ]