# Generated by Django 5.2.8 on 2026-02-11 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_add_updated_at_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_card', models.TextField(verbose_name='Rendered HTML card')),
                ('compressed_card', models.BinaryField(blank=True, null=True, verbose_name='Compressed card data')),
                ('game_name', models.CharField(db_index=True, max_length=255, verbose_name='Game name')),
                ('game_rating', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Game rating')),
                ('game_cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Cover URL')),
                ('game_type', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Game type')),
                ('genres_json', models.JSONField(default=list, verbose_name='Genres JSON')),
                ('platforms_json', models.JSONField(default=list, verbose_name='Platforms JSON')),
                ('perspectives_json', models.JSONField(default=list, verbose_name='Perspectives JSON')),
                ('keywords_json', models.JSONField(default=list, verbose_name='Keywords JSON')),
                ('themes_json', models.JSONField(default=list, verbose_name='Themes JSON')),
                ('game_modes_json', models.JSONField(default=list, verbose_name='Game modes JSON')),
                ('show_similarity', models.BooleanField(default=False, verbose_name='Show similarity')),
                ('similarity_percent', models.FloatField(blank=True, null=True, verbose_name='Similarity percent')),
                ('card_size', models.CharField(default='normal', max_length=20, verbose_name='Card size')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Cache key')),
                ('card_hash', models.CharField(db_index=True, max_length=64, verbose_name='Card hash')),
                ('hit_count', models.IntegerField(default=0, verbose_name='Hit count')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Last accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_cache', to='games.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Game card cache',
                'verbose_name_plural': 'Game card caches',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['game', 'is_active'], name='games_gamec_game_id_8ec83c_idx'), models.Index(fields=['cache_key', 'is_active'], name='games_gamec_cache_k_142253_idx'), models.Index(fields=['game_rating', 'is_active'], name='games_gamec_game_ra_dfb80c_idx'), models.Index(fields=['created_at', 'is_active'], name='games_gamec_created_bf2a09_idx'), models.Index(fields=['hit_count', 'is_active'], name='games_gamec_hit_cou_88a723_idx'), models.Index(fields=['card_size', 'is_active'], name='games_gamec_card_si_a38ed1_idx'), models.Index(fields=['show_similarity', 'is_active'], name='games_gamec_show_si_fed9e7_idx')],
            },
        ),
    ]
