# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0012_remove_gametype_model'),
    ]

    operations = [
        # Удаляем дублирующиеся поля
        migrations.RemoveField(
            model_name='game',
            name='game_type_old',
        ),
        # Поле game_type_new уже переименовано в game_type в миграции 0011
        # Поле game_type как ForeignKey уже удалено в миграции 0011
    ]