# Generated by Django 5.2.8 on 2026-02-13 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_gamecardcache'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamecardcache',
            name='games_gamec_card_si_a38ed1_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamecardcache',
            name='games_gamec_show_si_fed9e7_idx',
        ),
        migrations.RemoveField(
            model_name='gamecardcache',
            name='card_size',
        ),
        migrations.RemoveField(
            model_name='gamecardcache',
            name='show_similarity',
        ),
        migrations.RemoveField(
            model_name='gamecardcache',
            name='similarity_percent',
        ),
    ]
