# Generated by Django 5.2.8 on 2026-02-13 08:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_gamecardcache_games_gamec_card_si_a38ed1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_index=True, default=list, help_text='Materialized list of developer IDs for fast similarity search', size=None),
        ),
        migrations.AddField(
            model_name='game',
            name='game_mode_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_index=True, default=list, help_text='Materialized list of game mode IDs for fast similarity search', size=None),
        ),
        migrations.AddField(
            model_name='game',
            name='genre_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_index=True, default=list, help_text='Materialized list of genre IDs for fast similarity search', size=None),
        ),
        migrations.AddField(
            model_name='game',
            name='keyword_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_index=True, default=list, help_text='Materialized list of keyword IDs for fast similarity search', size=None),
        ),
        migrations.AddField(
            model_name='game',
            name='perspective_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_index=True, default=list, help_text='Materialized list of player perspective IDs for fast similarity search', size=None),
        ),
        migrations.AddField(
            model_name='game',
            name='theme_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_index=True, default=list, help_text='Materialized list of theme IDs for fast similarity search', size=None),
        ),
    ]
