# Generated by Django 5.2.8 on 2026-02-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_populate_materialized_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecardcache',
            name='template_version',
            field=models.CharField(default='v1', max_length=10, verbose_name='Template version'),
        ),
        migrations.AddIndex(
            model_name='gamecardcache',
            index=models.Index(fields=['template_version', 'is_active'], name='games_gamec_templat_ad20ba_idx'),
        ),
    ]
