# Generated by Django 5.2.8 on 2026-02-21 01:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_gamecardcache_template_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_cached_engine_count',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='engine_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_index=True, default=list, help_text='Materialized list of game engine IDs for fast similarity search', size=None),
        ),
        migrations.CreateModel(
            name='GameEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdb_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game engine',
                'verbose_name_plural': 'Game engines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='games_gamee_name_50475d_idx'), models.Index(fields=['igdb_id'], name='games_gamee_igdb_id_d97cc3_idx')],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='engines',
            field=models.ManyToManyField(blank=True, help_text='Game engines used in this game', related_name='games', to='games.gameengine'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['_cached_engine_count'], name='games_game__cached_afcca6_idx'),
        ),
    ]
