# Generated by Django 5.2.8 on 2026-04-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_add_cascade_delete_to_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSectionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Section key')),
                ('section_type', models.CharField(choices=[('search_platforms', 'Search Platforms'), ('search_genres', 'Search Genres'), ('search_keywords', 'Search Keywords'), ('search_themes', 'Search Themes'), ('search_perspectives', 'Search Perspectives'), ('search_game_modes', 'Search Game Modes'), ('search_engines', 'Search Engines'), ('search_game_types', 'Search Game Types'), ('search_date', 'Search Date Filter'), ('similarity_platforms', 'Similarity Platforms'), ('similarity_genres', 'Similarity Genres'), ('similarity_keywords', 'Similarity Keywords'), ('similarity_themes', 'Similarity Themes'), ('similarity_perspectives', 'Similarity Perspectives'), ('similarity_game_modes', 'Similarity Game Modes'), ('similarity_engines', 'Similarity Engines'), ('similarity_date', 'Similarity Date Filter')], db_index=True, max_length=50, verbose_name='Section type')),
                ('rendered_html', models.TextField(verbose_name='Rendered HTML')),
                ('data_hash', models.CharField(db_index=True, max_length=64, verbose_name='Data hash')),
                ('template_version', models.CharField(default='v1', max_length=10, verbose_name='Template version')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('hit_count', models.IntegerField(default=0, verbose_name='Hit count')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Last accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Filter section cache',
                'verbose_name_plural': 'Filter section caches',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['section_key', 'is_active'], name='games_filte_section_e3bc59_idx'), models.Index(fields=['section_type', 'is_active'], name='games_filte_section_7f46b0_idx'), models.Index(fields=['template_version', 'is_active'], name='games_filte_templat_a29129_idx'), models.Index(fields=['hit_count', 'is_active'], name='games_filte_hit_cou_09b84e_idx')],
            },
        ),
    ]
