# Generated by Django 5.2.8 on 2026-04-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_add_filter_section_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='height',
            field=models.SmallIntegerField(default=1080),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='width',
            field=models.SmallIntegerField(default=1920),
        ),
        migrations.AddIndex(
            model_name='screenshot',
            index=models.Index(fields=['igdb_id'], name='games_scree_igdb_id_251fdb_idx'),
        ),
    ]
