# Generated by Django 5.2.8 on 2026-04-08 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_safe_optimize_screenshot'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='screenshot',
            name='games_scree_created_0c075f_idx',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='created_at',
        ),
    ]
